### ISSUE TITLE
Joining a deleted room doesn't show an error

### ISSUE THREAD

**Issue by noahkw** [LenBanana/SyncStream_Angular#4]
Instead, it says nothing playing and the only visible sidebar button is the leave room one.

https://drecktu.be/room/dnal96zxrp

![grafik](https://user-images.githubusercontent.com/6728859/151609633-83fb22b3-e02d-47af-bba7-832a712d0b89.png)

**Comment by LenBanana** [comment]
Fixed in commit [7acb6dd](https://github.com/LenBanana/SyncStream_Angular/commit/7acb6ddb141657456a6c4c65caafb6eb3e2a0c1f)
