### ISSUE TITLE
Can't play YouTube shorts

### ISSUE THREAD

**Issue by noahkw** [LenBanana/SyncStream_Angular#6]
It says `An error occurred. Please try again later` trying to sync a YouTube short such as https://www.youtube.com/shorts/un4RTb6jhOI.

Edit: works when you manually edit the link to a regular one, i.e., https://www.youtube.com/watch?v=un4RTb6jhOI.

**Comment by LenBanana** [comment]
Fixed in backend with commit [dce3f18](https://github.com/LenBanana/SyncStream_API/commit/dce3f188c519425d46623fb2c969fd8dd92a0a68)
